DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.0025
  MAX_EPOCH: 100
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 32

MODEL:
  BACKBONE:
    NAME: "ViT-B/32"

TRAINER:
  VLTCOOP:
    CTX_INIT: "a photo of a"
    LAMBDA_TPA: 0.5
    LAMBDA_TDM: 0.25
    LAMBDA_VPA: 0.3
    LAMBDA_VDM: 0.15
    MAD_THRESHOLD: 1.5
    TEMPERATURE: 0.01
    N_CAPTIONS: 50

DATASET:
  NAME: "mix1"
  BASE_CLASS_IDS: [0, 1, 2, 3, 6, 7, 8, 10]
  NEW_CLASS_IDS: [4, 5, 9]
